spring.application.name=payment-service
server.port=8085

bank.security.jwt.secret=phase3-banking-shared-secret-change-in-prod-2026
bank.security.jwt.issuer=bank-platform-identity

management.endpoints.web.exposure.include=health,info
