spring.application.name=api-gateway
server.port=8080

bank.security.jwt.secret=phase3-banking-shared-secret-change-in-prod-2026
bank.security.jwt.issuer=bank-platform-identity

management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.mvc.routes[0].id=identity-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.mvc.routes[1].id=account-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/accounts/**

spring.cloud.gateway.mvc.routes[2].id=customer-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/customers/**

spring.cloud.gateway.mvc.routes[3].id=transaction-service
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/v1/transactions/**

spring.cloud.gateway.mvc.routes[4].id=payment-service
spring.cloud.gateway.mvc.routes[4].uri=http://localhost:8085
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/v1/payments/**

spring.cloud.gateway.mvc.routes[5].id=audit-service
spring.cloud.gateway.mvc.routes[5].uri=http://localhost:8086
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/v1/audit/**
