spring.application.name=api-gateway
server.port=${SERVER_PORT:8080}

bank.security.jwt.secret=${BANK_SECURITY_JWT_SECRET:phase3-banking-shared-secret-change-in-prod-2026}
bank.security.jwt.issuer=${BANK_SECURITY_JWT_ISSUER:bank-platform-identity}
bank.services.identity-service.url=${IDENTITY_SERVICE_URL:http://localhost:8081}
bank.services.account-service.url=${ACCOUNT_SERVICE_URL:http://localhost:8082}
bank.services.customer-service.url=${CUSTOMER_SERVICE_URL:http://localhost:8083}
bank.services.transaction-service.url=${TRANSACTION_SERVICE_URL:http://localhost:8084}
bank.services.payment-service.url=${PAYMENT_SERVICE_URL:http://localhost:8085}
bank.services.audit-service.url=${AUDIT_SERVICE_URL:http://localhost:8086}
bank.ops.prometheus.url=${PROMETHEUS_URL:http://localhost:9090}
bank.ops.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
bank.security-events.enabled=${API_EVENTS_ENABLED:true}
bank.security-events.topic=${API_EVENTS_TOPIC:api-events}
bank.security-events.service-name=${API_EVENTS_SERVICE_NAME:api-gateway}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
logging.file.name=${LOG_FILE_PATH:}
logging.pattern.level=%5p [service=${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]
