spring.application.name=account-service
server.port=8082

bank.security.jwt.secret=phase3-banking-shared-secret-change-in-prod-2026
bank.security.jwt.issuer=bank-platform-identity
bank.internal.api-key=phase5-internal-service-key-change-in-prod-2026
spring.datasource.url=jdbc:h2:file:./data/account-service-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
springdoc.swagger-ui.document-title=Account Swagger

management.endpoints.web.exposure.include=health,info
